[package]
name = "dagger"
version = "0.1.0"
authors = ["Dave Patrick Caberto"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
adw = { package = "libadwaita", version = "0.5", features = ["v1_4"] }
anyhow = "1.0.75"
async-fs = "2.1.0"
async-process = "2.0.1"
futures-util = { version = "0.3.29", features = ["io"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.7", package = "gtk4", features = ["gnome_45"] }
gtk_source = { package = "sourceview5", version = "0.7" }
tempfile = "3.8.1"
tracing = "0.1.37"
tracing-subscriber = "0.3"
