[package]
name = "dagger"
version = "0.1.0"
authors = ["Dave Patrick Caberto"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
adw = { package = "libadwaita", version = "0.5", features = ["v1_4"] }
anyhow = "1.0.75"
async-lock = "3.2"
futures-util = { version = "0.3.29", features = ["io"] }
futures-channel = "0.3.29"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
graphviz-sys = { path = "graphviz-sys" }
gsettings-macro = "0.1.20"
gtk = { version = "0.7", package = "gtk4", features = ["gnome_45"] }
gtk_source = { package = "sourceview5", version = "0.7", features = ["v5_10"] }
regex = "1.10.2"
tracing = "0.1.37"
tracing-subscriber = "0.3"
webkit = { package = "webkit6", version = "0.2.0", features = ["v2_42"] }
